#Le nom du compose 
name: demo-compose


# Description des différents containers
services:

  #Desription du container mysql
  mysql:
    image: mysql:8.0.45
    container_name: mysql
    environment:
      MYSQL_DATABASE: biblio
      MYSQL_ROOT_PASSWORD: root 
    volumes:
    #POur initialiser la base 
      #- ./bibliotek-init.sql:/docker-entrypoint-initdb.d/init.sql
    #POur persister les data apres supression / mise a jour du container
      - mysql-data:/var/lib/mysql
    networks:
      - quest
    ports:
      - 3307:3306
    healthcheck: #test pour verifier que le service soit pret
      test: ["CMD", "mysqladmin","ping","-h","localhost"]
      timeout: 3s
      retries: 10
      interval: 5s


  biblio-app:
    #image: biblio-app:latest
    build: ./biblio
    container_name: biblio-app
    networks:
      - quest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/biblio
      SPRING_DATASOURCE_USERNAME: root  
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - 8080:8080
    #dit au container java d'attendre la mise en place du container mysql
    depends_on:
      #- mysql
      mysql: #ici on attends que mysql demarre et que le service soit pret a être utilisé
        condition: service_healthy
      #postgres:
        #condition: service_healthy


networks:
  quest:
    name: quest-test

volumes:
  mysql-data:
    name: quest-mysql-data

  postgres-data:
    name: quest-postgres-data