name: demo-compose

services:
  mysql:
    image: mysql:8.0.45
    container_name: mysql
    environment:
      MYSQL_DATABASE: biblio
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - devops
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 3s
      retries: 10
      interval: 5s

  biblio-app:
    image: ajc/biblio
    build: ./biblio
    container_name: biblio-app
    networks:
      - devops
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/biblio
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy

  biblio-angular:
    image: ajc/biblio-angular
    container_name: biblio-angular
    networks:
      - devops
    ports:
      - 4200:80
    depends_on:
      - biblio-app

networks:
  devops:
    name: devops

volumes:
  mysql-data:
    name: devops-mysql-data