pipeline {
    agent {
        docker {
            image 'maven:3.9.6-eclipse-temurin-21'
            args '--network devops -v /root/.m2:/root/.m2'
        }
    }

    stages {
        

        stage('Build') {
            steps {
                dir('biblio') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('biblio') {
                    withSonarQubeEnv('sonar') {
                        sh 'mvn verify sonar:sonar -Dsonar.projectKey=biblio-boot'
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                waitForQualityGate abortPipeline: true
            }
        }
    }
}