pipeline {
    agent {
        docker {
            image 'node:20'
            args '--network devops'
        }
    }

    stages {

        stage('Install & Build') {
            steps {
                dir('biblio-angular') {
                    sh 'npm install'

                    withSonarQubeEnv('sonarqube-server') {
                        sh './node_modules/.bin/sonar-scanner -Dsonar.projectKey=biblio-angular'
                    }

                    sh 'npm run build'
                }
            }
        }

        stage('Docker build') {
            steps {
                dir('biblio-angular') {
                    sh 'docker build -t biblio-angular .'
                }
            }
        }

        stage('Docker deploy') {
            steps {
                // Se placer dans le répertoire (éventuellement) dans lequel se trouve le docker-compose.yml
                // dir('ANGULAR/quest-angular') {
                sh 'docker compose up -d --no-deps biblio-angular'
                // }
            }
        }
       
    }
}