pipeline {
    agent {
        docker {
            image 'node:20'
            args '--network devops'
        }
    }

    stages {

        stage('Install & Build') {
            steps {
                dir('biblio-angular') {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }

        stage('SonarQube') {
            agent {
                docker {
                    image 'sonarsource/sonar-scanner-cli:latest'
                    args '--network devops -u root'
                    reuseNode true
                }
            }
            steps {
                dir('biblio-angular') {
                    withSonarQubeEnv('SonarQube') {
                        sh '''
                            sonar-scanner \
                                -Dsonar.projectKey=biblio-angular \
                                -Dsonar.sources=src \
                                -Dsonar.exclusions=**/*.spec.ts,**/node_modules/**
                        '''
                    }
                }
            }
        }

        stage('Docker build') {
            steps {
                dir('biblio-angular') {
                    sh 'docker build -t biblio-angular .'
                }
            }
        }

        stage('Docker deploy') {
            steps {
                // Se placer dans le répertoire (éventuellement) dans lequel se trouve le docker-compose.yml
                // dir('ANGULAR/quest-angular') {
                sh 'docker compose up -d --no-deps biblio-angular'
                // }
            }
        }
       
    }
}